### ISSUE TITLE
Android: Missing buttons after cropping when you take full display photo

### ISSUE THREAD

**Issue by mohlerit** [WebsiteBeaver/capacitor-document-scanner#10]
Hello,
This plugin is very usefull and thank you for it. I have problem on Android. When I open document scanner on my Samsung Galaxy S20 FE, camera is set in full screen photo mode then after take photo I can not aprrove crop. Buttons are hide out of display or under photo and it is not possible to scrool down. When I set 9:16 screen photo modeeverything is ok. 

Here is GIF where I took photo Full screen and after I set up 9:16 screen and took photo again: https://ibb.co/3Fy1HYY 

Is it possible to set it screen strictly before run document scanner or some soloutions how to fix it? I cannot find solution.

Thank you for yor time.

Tested on: Samsung Galaxy S20 FE,  Android 12

**Comment by dmarcs** [comment]
That link doesn't seem to be working.

**Comment by mohlerit** [comment]
Interesting. It works for me. I add link on youtube.

https://www.youtube.com/watch?v=F75QIhZY7js

**Comment by dmarcs** [comment]
the buttons look visible to me

**Comment by dmarcs** [comment]
fixed in https://github.com/WebsiteBeaver/capacitor-document-scanner/releases/tag/1.0.1

https://github.com/WebsiteBeaver/android-document-scanner/commit/f2a9474b4edd04e7d704195e6427e0209c94e1e8
Set a minimum bottom control bar height, so that a really tall photo doesn't cut it off
