### ISSUE TITLE
Upgrade to Capacitor 5?

### ISSUE THREAD

**Issue by kgergooo** [WebsiteBeaver/capacitor-document-scanner#15]
hi! thanks for all your hard work, it's a really useful plugin, is there any plan to upgrade to capacitor 5?

**Comment by wimZ** [comment]
Same here.  Plugin works fine. 

Currently it blocks migrating to capacitor 5.

:)

**Comment by kgergooo** [comment]
Amazing, thanks for the new release!

**Comment by wimZ** [comment]
👍 Super thanks

28 mei 2023 17:20:17 David Marcus ***@***.***>:
