### ISSUE TITLE
New feature:  crop from side and top/bottom

### ISSUE THREAD

**Issue by wimZ** [WebsiteBeaver/capacitor-document-scanner#17]
Top scanner !. migrated from Cordova to Capacitor partly because of issues with scanning documents.

Would it be possible to crop 2 points in parallel like in the attached example.  (from Cordova document scanner)

In the example, the top and bottom were cropped by the middle touchpoint, the sides will be moved inward by the middle touchpoints to select only the white image.  

![crop](https://github.com/WebsiteBeaver/capacitor-document-scanner/assets/16089525/d7c95e73-7a8b-4cb6-a112-197f300afdd8)

**Comment by dmarcs** [comment]
Interesting idea, but I prefer 4 corners to keep things simpler.
